### ISSUE TITLE
setEnabled(false) does not disable editing

### ISSUE THREAD

**Issue by TatuLund** [vaadin/vaadin-grid-pro-flow#25]
GridPro implements HasEnabled interface, and hence has setEnabled(..) and isEnabled() methods. setEnabled(false) however seems not to have effect on editing. I.e. editing is possible even when setEnabled(false)

Use the following example to reproduce

```
import com.vaadin.flow.component.gridpro.GridPro;
import com.vaadin.flow.component.orderedlayout.FlexLayout;
import com.vaadin.flow.router.*;
import com.vaadin.flow.server.PWA;

@Route("")
@PWA(name = "Project Base for Vaadin Flow with CDI", shortName = "Project Base")
@PageTitle("Pinnacle Professional")
@SuppressWarnings("unused" /*main entry point!*/)
public class MainView extends FlexLayout implements RouterLayout {

    public MainView() {
        GridPro<String[]> minimalGrid = new GridPro<>();
        minimalGrid.addEditColumn((ar) -> ar[0])
            .text((ar, s) -> ar[0] =s);
        minimalGrid.setEnabled(false);
        minimalGrid.setItems(new String[]{"abc"}, new String[]{"def"});
        add(minimalGrid);
    }
}
```

**Comment by TatuLund** [comment]
Is this related to https://github.com/vaadin/vaadin-grid-flow/issues/519 ?

**Comment by web-padawan** [comment]
See also https://github.com/vaadin/vaadin-grid-pro/issues/85

**Comment by web-padawan** [comment]
We can consider implementing `disabled` attribute in `vaadin-grid-pro` as an "internal" feature.

There are some "internal" attributes set by the grid itself: `navigating` and `interacting`.
So maybe the internal attribute meant to be used by Grid Pro Flow is OK.

The "readonly" feature mentioned in the above comment is different in the sense that it's submitted as specific to the column, while what we need here is to disable all the columns.
