### ISSUE TITLE
Add attribute to editable cells to improve themability

### ISSUE THREAD

**Issue by juuso-vaadin** [vaadin/vaadin-grid-pro-flow#70]
Currently there is no way to target the editable cells of Grid Pro.

Usability of Grid Pro is rather poor because there are no indicators for editable columns. Adding an attribute to cells within editable column would allow defining hover styles or other highlights.

**Comment by web-padawan** [comment]
Done by vaadin/vaadin-grid-pro#72 and included to 3.1.0.beta1

Use the following CSS to `themeFor="vaadin-grid-pro"`:

```css
[part~="editable-cell"] {
  // cell styles
}

[part~="editable-cell"]  ::slotted(vaadin-grid-cell-content) {
  // cell content styles
}
```

The web component version containing this feature will be also used in 2.1.0.
So, this is available in Vaadin 16 and will be also in Vaadin 14.3.
